// packages/core/templates/template-solid-ts/src/content/index.tsx
import { render } from 'solid-js/web';
import type { ContentScriptConfig } from 'web-extend';
import App from './App';

let root = document.getElementById('web-extend-content');
if (!root) {
  root = document.createElement('div');
  root.id = 'web-extend-content';
  document.body.appendChild(root);
  render(() => <App />, root);
}

export const config: ContentScriptConfig = {
  matches: ['https://developer.mozilla.org/*'],
};

// packages/cli/templates/template-react-ts/src/content/index.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import type { ContentScriptConfig } from '@web-extend/rsbuild-plugin';
import App from './App';

let rootEl = document.getElementById('web-extend-content');
if (!rootEl) {
  rootEl = document.createElement('div');
  rootEl.id = 'web-extend-content';
  document.body.appendChild(rootEl);
  const root = createRoot(rootEl);
  root.render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}

export const config: ContentScriptConfig = {
  matches: ['https://developer.mozilla.org/*'],
};
