// packages/cli/templates/template-svelte-ts/src/devtools/panels/font-picker/App.svelte
<main>
  <div class="content">
    <h1>WebExtend + Svelte</h1>
    <p>This is a panel page.</p>
  </div>
</main>

<style>
  .content {
    text-align: center;
    padding: 12px;
  }

  .content h1 {
    font-size: 1.8rem;
    font-weight: 700;
  }

  .content p {
    font-size: 1.2rem;
    font-weight: 400;
    opacity: 0.5;
  }
</style>

// packages/cli/templates/template-vue-ts/src/options/App.vue
<template>
  <div class="content">
    <h1>WebExtend + Vue</h1>
    <p>This is an options page.</p>
  </div>
</template>

<style scoped>
.content {
  text-align: center;
  padding: 12px;
}

.content h1 {
  font-size: 1.8rem;
  font-weight: 700;
}

.content p {
  font-size: 1.2rem;
  font-weight: 400;
  opacity: 0.5;
}
</style>
