// packages/core/templates/template-preact-ts/src/content/index.tsx
import type { ContentScriptConfig } from 'web-extend';
import { render } from 'preact';
import App from './App';

let root = document.getElementById('web-extend-content');
if (!root) {
  root = document.createElement('div');
  root.id = 'web-extend-content';
  document.body.appendChild(root);
  render(<App />, root);
}

export const config: ContentScriptConfig = {
  matches: ['https://developer.mozilla.org/*'],
};

// packages/core/templates/template-solid-ts/src/content/index.tsx
import { render } from 'solid-js/web';
import type { ContentScriptConfig } from 'web-extend';
import App from './App';

let root = document.getElementById('web-extend-content');
if (!root) {
  root = document.createElement('div');
  root.id = 'web-extend-content';
  document.body.appendChild(root);
  render(() => <App />, root);
}

export const config: ContentScriptConfig = {
  matches: ['https://developer.mozilla.org/*'],
};
